name: Release

on:
  push:
    branches:
      - master
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Enable Corepack
        run: corepack enable
      - name: Prepare correct Yarn version
        run: corepack prepare yarn@4.6.0 --activate
      - name: Yarn install
        run: yarn install
      - name: Yarn build
        run: yarn build
      - name: Make the production plugin bundle
        run: |
          release_version=$(cat package.json | jq -r '.version')
          echo "RELEASE_VERSION=$release_version" >> $GITHUB_ENV
          yarn
          yarn build
      - name: Perform Github Release
        uses: softprops/action-gh-release@v2
        with:
          name: v${{ env.RELEASE_VERSION }}
          tag_name: v${{ env.RELEASE_VERSION }}
          generate_release_notes: true
          files: |
            dist/*.tar.gz
